version: '3'

services:
  influxdb:
    image: influxdb:1.4.2
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.4.5
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp" 

  kapacitor:
    image: kapacitor:1.4.0
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"

  chronograf:
    image: chronograf:1.3.10.0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor

  influxdb-cli:
    image: influxdb:1.4.2
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb

  kapacitor-cli:
    image: kapacitor:1.4.0
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor